services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"              # extern erreichbar
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: awjefipasdfö823ä#3
      MONGO_INITDB_DATABASE: appdb # wird beim Init angelegt
    volumes:
      - mongo_data:/data/db        # persistentes Volume
      - ./init:/docker-entrypoint-initdb.d:ro
    command: ["--bind_ip_all"]     # erlaubt externe Verbindungen
    # optional absichern: nur internes Netz exposen & reverse proxy/ssh-tunnel nutzen
    # networks:
    #   - internal

volumes:
  mongo_data:
    name: mongo_data
# networks:
#   internal:
#     driver: bridge
